name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend (FastAPI)
        - Frontend (Next.js)
        - Database (PostgreSQL)
        - Docker/Infrastructure
        - Documentation
        - CI/CD
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major feature broken)
        - Medium (Minor feature broken)
        - Low (Cosmetic issue)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: v1.0.0

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Local Development
        - Docker Compose
        - Staging
        - Production
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (for frontend issues)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - N/A
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I can reproduce this issue consistently
          required: false