"""Add factory_shifts table for shift management

Revision ID: 8525b0c5b893
Revises: 006_add_factory_breaks
Create Date: 2025-12-05 15:35:58.192287+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8525b0c5b893'
down_revision: Union[str, None] = '006_add_factory_breaks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('shift_premium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shift_premium_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factory_shifts_factory', 'factory_shifts', ['factory_id'], unique=False)
    op.create_index(op.f('ix_factory_shifts_id'), 'factory_shifts', ['id'], unique=False)
    op.drop_index('ix_factory_breaks_factory_id', table_name='factory_breaks')
    op.create_index('ix_factory_breaks_factory', 'factory_breaks', ['factory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_factory_breaks_factory', table_name='factory_breaks')
    op.create_index('ix_factory_breaks_factory_id', 'factory_breaks', ['factory_id'], unique=False)
    op.drop_index(op.f('ix_factory_shifts_id'), table_name='factory_shifts')
    op.drop_index('ix_factory_shifts_factory', table_name='factory_shifts')
    op.drop_table('factory_shifts')
    # ### end Alembic commands ###
