"""add_company_shifts_and_inheritance_flag

Revision ID: 6eb7f275e62b
Revises: 8525b0c5b893
Create Date: 2025-12-05 15:53:48.152503+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb7f275e62b'
down_revision: Union[str, None] = '8525b0c5b893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False, comment='シフト名 (例: 昼勤, 夜勤, 第3シフト)'),
    sa.Column('shift_start', sa.Time(), nullable=True, comment='シフト開始時間'),
    sa.Column('shift_end', sa.Time(), nullable=True, comment='シフト終了時間'),
    sa.Column('shift_premium', sa.Numeric(precision=10, scale=2), nullable=True, comment='シフト手当金額（円）'),
    sa.Column('shift_premium_type', sa.String(length=50), nullable=True, comment='手当種別 (時給/日給/月額)'),
    sa.Column('description', sa.Text(), nullable=True, comment='シフトの説明・備考'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='表示順序'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_shifts_company_id'), 'company_shifts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_shifts_id'), 'company_shifts', ['id'], unique=False)
    op.create_index(op.f('ix_company_shifts_is_active'), 'company_shifts', ['is_active'], unique=False)
    op.add_column('factories', sa.Column('use_company_shifts', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='True: 企業のシフトを継承 / False: 工場独自シフトを使用'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'use_company_shifts')
    op.drop_index(op.f('ix_company_shifts_is_active'), table_name='company_shifts')
    op.drop_index(op.f('ix_company_shifts_id'), table_name='company_shifts')
    op.drop_index(op.f('ix_company_shifts_company_id'), table_name='company_shifts')
    op.drop_table('company_shifts')
    # ### end Alembic commands ###
